# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6195b2c5a153dab67e43db0f87265dc512b120f035705c1280c75b9a0c5e9a214f4ec17b4fa06ea28ef33a782fe1456afe9ceefe8421dc282e47f32ecefe096

test:
  secret_key_base: bf08253f89ae278e7e28bc142667d19bf4d8f3fba5b6af9b6624c172a87140b7bf73333a1aa0063ba133f255308a90b3d2ba17baf6c30d91308301cfe0bc582e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
